export const schema = {
  models: {
    ReviewsRating: {
      name: "ReviewsRating",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        review: {
          name: "review",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        stars: {
          name: "stars",
          isArray: false,
          type: "Int",
          isRequired: false,
          attributes: [],
        },
        userId: {
          name: "userId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "ReviewsRatings",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                allow: "public",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    Payment: {
      name: "Payment",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        paymentStatus: {
          name: "paymentStatus",
          isArray: false,
          type: "Boolean",
          isRequired: true,
          attributes: [],
        },
        orderId: {
          name: "orderId",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        userID: {
          name: "userID",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Payments",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "key",
          properties: {
            name: "byUser",
            fields: ["userID"],
          },
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                allow: "public",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    Order: {
      name: "Order",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        orderItems: {
          name: "orderItems",
          isArray: false,
          type: "AWSJSON",
          isRequired: true,
          attributes: [],
        },
        Cart: {
          name: "Cart",
          isArray: false,
          type: {
            model: "Cart",
          },
          isRequired: false,
          attributes: [],
          association: {
            connectionType: "BELONGS_TO",
            targetNames: ["orderCartId"],
          },
        },
        orderDetails: {
          name: "orderDetails",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        orderStatus: {
          name: "orderStatus",
          isArray: false,
          type: "Boolean",
          isRequired: true,
          attributes: [],
        },
        Payment: {
          name: "Payment",
          isArray: false,
          type: {
            model: "Payment",
          },
          isRequired: false,
          attributes: [],
          association: {
            connectionType: "HAS_ONE",
            associatedWith: ["id"],
            targetNames: ["orderPaymentId"],
          },
        },
        userID: {
          name: "userID",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        orderCartId: {
          name: "orderCartId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
        orderPaymentId: {
          name: "orderPaymentId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "Orders",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "key",
          properties: {
            name: "byUser",
            fields: ["userID"],
          },
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                allow: "public",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    Cart: {
      name: "Cart",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        productId: {
          name: "productId",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        productQty: {
          name: "productQty",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        productPrice: {
          name: "productPrice",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        cartTotal: {
          name: "cartTotal",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        User: {
          name: "User",
          isArray: false,
          type: {
            model: "User",
          },
          isRequired: false,
          attributes: [],
          association: {
            connectionType: "BELONGS_TO",
            targetNames: ["cartUserId"],
          },
        },
        Order: {
          name: "Order",
          isArray: false,
          type: {
            model: "Order",
          },
          isRequired: false,
          attributes: [],
          association: {
            connectionType: "HAS_ONE",
            associatedWith: ["id"],
            targetNames: ["cartOrderId"],
          },
        },
        cartStatus: {
          name: "cartStatus",
          isArray: false,
          type: "Boolean",
          isRequired: true,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        cartUserId: {
          name: "cartUserId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
        cartOrderId: {
          name: "cartOrderId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "Carts",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                allow: "public",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    Product: {
      name: "Product",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        description: {
          name: "description",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        productImageUrls: {
          name: "productImageUrls",
          isArray: true,
          type: "String",
          isRequired: true,
          attributes: [],
          isArrayNullable: false,
        },
        price: {
          name: "price",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        quantity: {
          name: "quantity",
          isArray: false,
          type: "Int",
          isRequired: true,
          attributes: [],
        },
        inStock: {
          name: "inStock",
          isArray: false,
          type: "Boolean",
          isRequired: true,
          attributes: [],
        },
        categoryID: {
          name: "categoryID",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        sizes: {
          name: "sizes",
          isArray: true,
          type: "String",
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
        },
        colors: {
          name: "colors",
          isArray: true,
          type: "String",
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
        },
        hasSizes: {
          name: "hasSizes",
          isArray: false,
          type: "Boolean",
          isRequired: true,
          attributes: [],
        },
        hasColors: {
          name: "hasColors",
          isArray: false,
          type: "Boolean",
          isRequired: true,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Products",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "key",
          properties: {
            name: "byCategory",
            fields: ["categoryID"],
          },
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                allow: "public",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    Category: {
      name: "Category",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        description: {
          name: "description",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        isParent: {
          name: "isParent",
          isArray: false,
          type: "Boolean",
          isRequired: true,
          attributes: [],
        },
        parentCategoryId: {
          name: "parentCategoryId",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        categoryImageUrl: {
          name: "categoryImageUrl",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        Products: {
          name: "Products",
          isArray: true,
          type: {
            model: "Product",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: ["categoryID"],
          },
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Categories",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                allow: "public",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    User: {
      name: "User",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        firstName: {
          name: "firstName",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        lastName: {
          name: "lastName",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        email: {
          name: "email",
          isArray: false,
          type: "AWSEmail",
          isRequired: true,
          attributes: [],
        },
        address: {
          name: "address",
          isArray: false,
          type: "AWSJSON",
          isRequired: true,
          attributes: [],
        },
        isActive: {
          name: "isActive",
          isArray: false,
          type: "Boolean",
          isRequired: true,
          attributes: [],
        },
        userType: {
          name: "userType",
          isArray: false,
          type: {
            enum: "UserType",
          },
          isRequired: false,
          attributes: [],
        },
        Cart: {
          name: "Cart",
          isArray: false,
          type: {
            model: "Cart",
          },
          isRequired: false,
          attributes: [],
          association: {
            connectionType: "HAS_ONE",
            associatedWith: ["id"],
            targetNames: ["userCartId"],
          },
        },
        Orders: {
          name: "Orders",
          isArray: true,
          type: {
            model: "Order",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: ["userID"],
          },
        },
        Payments: {
          name: "Payments",
          isArray: true,
          type: {
            model: "Payment",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: ["userID"],
          },
        },
        ReviewsRating: {
          name: "ReviewsRating",
          isArray: false,
          type: {
            model: "ReviewsRating",
          },
          isRequired: false,
          attributes: [],
          association: {
            connectionType: "HAS_ONE",
            associatedWith: ["id"],
            targetNames: ["userReviewsRatingId"],
          },
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        userCartId: {
          name: "userCartId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
        userReviewsRatingId: {
          name: "userReviewsRatingId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "Users",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                allow: "public",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    Store: {
      name: "Store",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        logoUrl: {
          name: "logoUrl",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        fontType: {
          name: "fontType",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        hero: {
          name: "hero",
          isArray: true,
          type: "String",
          isRequired: true,
          attributes: [],
          isArrayNullable: true,
        },
        description: {
          name: "description",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        ownerEmail: {
          name: "ownerEmail",
          isArray: false,
          type: "AWSEmail",
          isRequired: false,
          attributes: [],
        },
        ownerAddress: {
          name: "ownerAddress",
          isArray: false,
          type: "AWSJSON",
          isRequired: false,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Stores",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                allow: "public",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
  },
  enums: {
    UserType: {
      name: "UserType",
      values: ["ADMIN", "CUSTOMER"],
    },
  },
  nonModels: {},
  codegenVersion: "3.4.4",
  version: "9b9e11977acc40e1d62047e580ddb259",
};
